### ISSUE TITLE
Build ASE Atoms from supercell?

### ISSUE THREAD

**Issue by craldaz** [LaurentRDC/crystals#1]
Hi, 
I'm a new user to ASE and Crystal

I created a supercell and when I try to create ase_atoms from that I get the error

AttributeError: 'Supercell' object has no attribute 'lattice_vectors'

How can I create ase_atoms from the supercell?

**Comment by LaurentRDC** [comment]
Hello!

In this particular case, the best thing to do is to create a crystal from the supercell. Example with graphite and a 2x2x2 supercell:

```python
from crystals import Crystal, ase_atoms

graphite = Crystal.from_database('C')
supercell = graphite.supercell(2,2,2)

large_crystal = Crystal(unitcell=supercell, lattice_vectors=graphite.lattice_vectors)
ase_graphite = ase_atoms(large_crystal)
```

Let me know if this is good enough for you!

**Comment by LaurentRDC** [comment]
@craldaz did you have time to try this?

**Comment by LaurentRDC** [comment]
Closed for lack of activity. I'm happy to re-open it if the solution is unclear.
