### ISSUE TITLE
supercell creation

### ISSUE THREAD

**Issue by errhernandez** [LaurentRDC/crystals#11]
Hello, 

This is a very nice piece of software; thank you very much for providing it. I have come across a small issue, not necessarily an error but error-prone at least: the Crystal object allows one to construct a supercell, which results in a new Crystal object. One would naturally tend to think that the supercell would have appropriately scaled lattice parameters, but in fact the supercell crystal object has the same lattice parameters as those of the original Crystal object. Of course it is easy enough to scale the lattice parameters, but it would be better if the Crystal object constructed when using supercell automatically generated the scaled parameters, I think.

Cheers!

**Comment by LaurentRDC** [comment]
Hello,

This is actually a feature, not a bug. The lattice parameters mark the periodicity of the lattice. With a supercell, you still have the same periodicity. 

This behavior is important for many other applications where `crystals` is used. For example, simulating diffraction patterns using the static structure factor should give identical results if using a unit cell or a super cell.

Note, however, that the `Crystal.supercell()` method returns a [different object](https://github.com/LaurentRDC/crystals/blob/master/crystals/crystal.py#L797) than a `Crystal`. If it helps, I could add a new attribute called `scaled_lattice_vectors` or something like this, which does exactly what you want: lattice vectors which are scaled by the supercell dimensions (in units of lattice vectors).
 
What do you think?

**Comment by errhernandez** [comment]
Hello, 

Right, I suspected something like this but thought I would just check. I think the question arises because we have slightly different perspectives, crystallography on one hand and atomistic simulation on the other. You regard lattice parameters as defining the translational symmetry, while I regard them as defining a simulation box. Anyway, it is useful because I had not realised that Crystal.supercell() does not return a Crystal. 

As for adding a new attribute, scaled_lattice_vectors, well, it may be useful if it is not too much effort, and it may serve to draw attention to the fact that lattice_vectors continue to be those of the unit cell and not those of the supercell. Anyway, once one knows, it is trivial to do it by hand, so no big deal. It might be worthwhile though to point it out in the documentation.

Thank you for your quick response. 

Eduardo

**Comment by LaurentRDC** [comment]
Thank you for your feedback. I will update the documentation and add the attribute when I have some time. 

Don't hesitate to open other issues if you have more questions and feedback!

Laurent

**Comment by LaurentRDC** [comment]
Release 1.5.0 contains the changes discussed here and more. Give it a try
