### ISSUE TITLE
Version not displayed in created CIF file

### ISSUE THREAD

**Issue by Cs137** [LaurentRDC/crystals#14]
Hi Laurent,

many thanks for your nice package! 

I recognised that the version field in a created CIF file is a not treated as it should. The variable name is not replaced with an actual version number, the output in the "cite" section of the created file looks as follows (version 1.6.1):

```text
# File generated by `crystals` {__version__}, documented at https://crystals.rtfd.io
# Reference:  L. P. René de Cotret et al, An open-source software ecosystem for the interactive exploration
#             of ultrafast electron scattering data, Advanced Structural and Chemical Imaging 4:11 (2018) DOI: 10.1186/s40679-018-0060-y.
```

Cheers,
Christian

**Comment by LaurentRDC** [comment]
The appropriate `crystals` version will be correctly included in CIFs in version 1.6.2 and beyond, which is being released today. Thanks!
