### ISSUE TITLE
parsers.py:638: Incloplete warning message

### ISSUE THREAD

**Issue by Cs137** [LaurentRDC/crystals#15]
The output of the UserWarning is not shown as desired when it is raised during the creation of a CIF file. I assume the "warnings.warn(" is not supposed to be displayed:

```
crystals/parsers.py:638: UserWarning: The number of equivalent sites is not in line with the database. The file might be incomplete
  warnings.warn(
```

A suggestion for an improvement besides removing the undesired string is to show also `os.basename(file_path)` in the message. In `Crystal.to_cif` batch creations it is impossible to assign the error message to its source, in the way how it is currently implemented (version 1.6.1).

**Comment by LaurentRDC** [comment]
Thank you for your suggestion. I will add the filename to the warning.

> I assume the "warnings.warn(" is not supposed to be displayed:

Although this looks strange, you assume wrong. This is the standard behavior of `warnings.warn`. Consider this script:

```python
import warnings; warnings.warn("This is a warning.")
```

When I run it, I get:

```bash
laurent:~$ python -m test
/home/laurent/test.py:1: UserWarning: This is a warning.
  warnings.warn("This is a warning.")
```

**Comment by LaurentRDC** [comment]
The improvement to the warning you mentioned will come in version 1.6.2, which is being released today. Thanks!

**Comment by Cs137** [comment]
> Although this looks strange, you assume wrong. This is the standard behavior of `warnings.warn`. Consider this script:
> 
> ```python
> import warnings; warnings.warn("This is a warning.")
> ```
> 
> When I run it, I get:
> 
> ```shell
> laurent:~$ python -m test
> /home/laurent/test.py:1: UserWarning: This is a warning.
>   warnings.warn("This is a warning.")
> ```

The mentioned error message returns `warnings.warn(` at the end without showing any massage behind the parenthesis, which is not the case in the example that you added. However, many thanks for picking up my suggestion and its prompt implementation!

**Comment by LaurentRDC** [comment]
Good point. Looks like this is because of a newline in the source Python code. E.g.:

```python
import warnings
warnings.warn(
    "This is a warning message."
)
```

```bash
laurent:~$ python -m test
/home/laurent/test.py:2: UserWarning: This is a warning message.
  warnings.warn(
```

I'm using an autoformatter (`black`) which inserts this newline because the warning is long. It'll have to stay this way for now.
