### ISSUE TITLE
Type annotations

### ISSUE THREAD

**Issue by eggplants** [LaurentRDC/crystals#16]
I would like to add type annotations and [provide](https://peps.python.org/pep-0561/) type information.

![image](https://user-images.githubusercontent.com/42153744/213413747-9cb6ba24-6362-4ca6-a4cc-bcaf70f77166.png)

**Comment by LaurentRDC** [comment]
Hi eggplants,
That's going to be a lot of work. I'm not going to spend time on this myself, but I'm happy to review pull requests that add type annotations.
