### ISSUE TITLE
Load file with bytes, str, IO

### ISSUE THREAD

**Issue by eggplants** [LaurentRDC/crystals#17]
Currently, `crystals.Crystal.from_*` methods accepts Path-like objects.

I would like to pass `bytes`, `str`, and file `IO` objects.

**Comment by LaurentRDC** [comment]
Hi eggplants,

From the documentation of [`os.PathLike`](https://docs.python.org/3/library/os.html#os.PathLike), you'll see that it includes many types including `Path`, `str` and `bytes`.

That means that you can already write code like this:

```python
from pathlib import Path
from crystals import Crystal

crystal.from_cif( Path('home') / 'foo' / 'bar.cif' )  # Path
crystal.from_cif( 'home/foo/bar.cif' )                # str
crystal.from_cif( b'home/foo/bar.cif' )               # bytes
```

I don't know what `IO` is though.

**Comment by eggplants** [comment]
Like [`gemmi.read_pdb_string`](https://project-gemmi.github.io/python-api/#read_pdb_string), I mean:

```python
# io.BytesIO, IO[bytes]
crystal.from_cif(open('home/foo/bar.cif'))

# bytes
crystal.from_cif(open('home/foo/bar.cif').read())

# str
crystal.from_cif(open('home/foo/bar.cif').read().decode('utf-8'))
crystal.from_cif('''
data_AF-A0A1C1D177-F1
#
_entry.id AF-A0A1C1D177-F1
#
loop_
_atom_type.symbol
C
N
O
S
#
loop_
_audit_author.name
_audit_author.pdbx_ordinal
...
''')
```

**Comment by LaurentRDC** [comment]
Ahhh I see what you mean.

I see no use for this, so I won't add the support for it myself. However, I'm always happy to review pull requests if this is important to you.

**Comment by eggplants** [comment]
This feature is useful to parse the content without extracting archived file, especially for very large dataset.
