### ISSUE TITLE
How can I get assymetric unit?

### ISSUE THREAD

**Issue by bokertof** [LaurentRDC/crystals#2]
Hello! I faced the problem that I've not found functions to get assymetric part from CIF i.e. only atoms are listed inside CIF file without applied symmetry operations. Can you help me with that issue? Or hasn't such function implemented yet?

maybe you can add option in this function to return crystal without `symmetry_expansion`?

```
def from_cif(cls, path, **kwargs):

        with CIFParser(filename=path) as parser:
            return cls(
                unitcell=symmetry_expansion(
                    parser.atoms(), parser.symmetry_operators()
                ),
                lattice_vectors=parser.lattice_vectors(),
                source=str(path),
                **kwargs,
            )
```

**Comment by LaurentRDC** [comment]
Hi @bokertof,

There isn't a function to do this easily yet :)

If you built a `Crystal` without symmetry operations, I'm afraid that the symmetry-determination functions would not work properly, and it wouldn't be obvious why from a debugging point-of-view. I could create a new class called `AsymmetricCell` instead, so that it is obvious what's going on.

Ultimately, what do you want to do with the asymmetric cell?

**Comment by bokertof** [comment]
> Hi @bokertof,
> 
> There isn't a function to do this easily yet :)
> 
> If you built a `Crystal` without symmetry operations, I'm afraid that the symmetry-determination functions would not work properly, and it wouldn't be obvious why from a debugging point-of-view. I could create a new class called `AsymmetricCell` instead, so that it is obvious what's going on.
> 
> Ultimately, what do you want to do with the asymmetric cell?

I want to get coords of all bounded atoms for some another specified atom. For example, for zinc atom get all atoms which has bonds with zinc. If I try to do it on unit cell I get several the same zinc atoms and its surroundings (and also new issue appears that some bounded with zinc atoms are in the neighboring cell so bonds can't be calculated). In a nutshell, I want to do it only for asymmetric unit properly

**Comment by LaurentRDC** [comment]
Ok. When I have some time, I will write a new class which does everything a Crystal does , minus the things that require a full unit cell.

*For now*, you can list atoms in the asymmetric cell like this:

```python
from crystals import CIFParser

with CIFParser('wtv.cif') as parser:
    asym_cell = list(parser.atoms())
```

Then, `asym_cell` is the list asymmetric cell atoms only.

**Comment by bokertof** [comment]
@LaurentRDC  Thank you! It works now 👍 
So, for further cartesian distances calculations I need add lattice vectors:

````
from crystals import CIFParser

with CIFParser('wtv.cif') as parser:
    lattice_vectors = parser.lattice_vectors()
    asym_cell = list(parser.atoms())
    
    for atom in asym_cell:
        atom.lattice.lattice_vectors = lattice_vectors
````

Also, every similar packages with CIF-parsers return list of atoms without their numbers, i.e. only element and its coordinates and it's not clear what this certain atom is (C1, C42 or C1432), that'd be great advantage for your library, if you implemented this feature. For instance, by adding extra parameter into `Atom class` discribing its name (like in cif file there're atom's name and its nature).

**Comment by LaurentRDC** [comment]
This feature already exists! Although because your use-case was never considered, you have to do a little bit extra work

To get cartesian distances:

```python
from crystals import CIFParser, distance_cartesian, Lattice

with CIFParser('wtv.cif') as parser:
    lattice = Lattice(parser.lattice_vectors())
    asym_cell = list(parser.atoms())

# Because you are dealing with atoms outsideo f a `Crystal`, you need to
# set them on a particular lattice
for atm in asym_cell:
    atm.lattice = lattice

# Example of distance
atm1, atm2, *_ = asym_cell
print('Distance:', distance_cartesian(atm1, atm2), ' Angstroms')
```

>  it's not clear what this certain atom is (C1, C42 or C1432), that'd be great advantage for your library, if you implemented this feature. For instance, by adding extra parameter into Atom class discribing its name (like in cif file there're atom's name and its nature).

Technically, there is a parameter in the `Atom` class for this purpose (the `tag` parameter), but I never really used it. I will consider making use of it like you suggest.

**Comment by LaurentRDC** [comment]
I'm going to close this for now, as I personally don't need this feature. I'm happy to receive pull requests if someone has the desire to see this "tagging" of atoms go through.
