### ISSUE TITLE
Git of pinkindexer not accessable

### ISSUE THREAD

**Issue by KeysBit** [LaurentRDC/crystals#20]
Tried to build from source. Found the link of https://stash.desy.de/users/gevorkov/repos/pinkindexer not accessable. But I found the link  https://gitlab.desy.de/thomas.white/pinkindexer. Unfortunately it seems can`t be used.

**Comment by KeysBit** [comment]
fixed by adding
```
#include <cstdint>
```
in `pinkindexer/src/ReflectionsInRangeFinder.cpp` and `pinkindexer/include/Sinogram.h`

Issue keeps opening for fixing on future by someone or close if repo owner wants.

**Comment by LaurentRDC** [comment]
Hi KeysBit,

Thank you for bringing this to my attention.

Support for pinkindexer was a real pain and made everything more complex, for very little benefit. I have elected to remove support for pinkindexer.
