### ISSUE TITLE
Reading the site-occupancy data from CIF files

### ISSUE THREAD

**Issue by azkhadiev** [LaurentRDC/crystals#3]
Looks like "crystals" package is not able to read a site-occupancy data from the CIF files. 
I tried to load the CIF file and read the occupancy of the atom by the lines:
arb_crystal = crystals.Crystal.from_cif('Arb_cry.cif')
list(arb_crystal)[0].occupancy

It shows 1.0 occupancy of all atoms in unit cell, whereas several of them have occupancy smaller than 1.0. How one can fix that?

**Comment by LaurentRDC** [comment]
Hello!

As of version 1.1.1, the occupancy of each site defaults to 1 (as you saw). I wrote the CIF parser a while ago, and never updated it.

I can update the parser today. Can you point me to a CIF file which has occupancies that are not 1.0?

**Comment by azkhadiev** [comment]
Thank you for the fast answer! Iy would be good to have this parser. Please, find in attached the CIF file (just change the .docx
[NiMnCoO4.docx](https://github.com/LaurentRDC/crystals/files/4772136/NiMnCoO4.docx)
 to .cif)

**Comment by LaurentRDC** [comment]
Thank you for this file!

Is it yours? If so, do you give me permission to include it in crystals' test suite?

Otherwise I will create an artificial CIF file.

Edit: Don't worry about it, I used an artificially-modified file.

**Comment by LaurentRDC** [comment]
Allright, I have released a new version (1.1.2) that addresses your concerns. It will be available via `conda` tomorrow. If you prefer to use `pip`, you can already [install it](https://pypi.org/project/crystals/):

```bash
pip install --upgrade crystals
```

Let me know if it works for you.

**Comment by azkhadiev** [comment]
Dear Laurent,

Thank you for your corrections. Unfortunately, I took this CIF file from ICSD database (https://icsd.fiz-karlsruhe.de/) and I am not sure that this file could be used freely without ICSD permission. But there are several open databases, where CIF files are absolutely available. Here is an example of Anorthite CIF file (http://rruff.geo.arizona.edu/AMS/CIF_text_files/00012_cif.txt) where occupancies are also presented. I am not absolutely sure, but maybe somebody will also ask you to include the possibility of parsing "anisotropic atomic displacement parameters" from CIF files.

Everything is working now, "crystals" takes occupancies from CIF files.

Thank you again for your work!
