### ISSUE TITLE
Forbidden Miller indices

### ISSUE THREAD

**Issue by StarostinV** [LaurentRDC/crystals#4]
Thank you for such a great package! Is there a functionality to filter out forbidden Miller indices?

**Comment by LaurentRDC** [comment]
Hi Vladimir!

There is no such functionality right now. If you want to get something working quickly, you can do something like this:
```python
from crystals import Crystal
cryst = Crystal.from_file(...)

def allowed(h, k, l):
    # calculate structure factor and check that it is not 0
    return True

# All allowed reflections with reciprocal length less than 10 inverse Angstroms
allowed_reflections = [refl for refl in cryst.bounded_reflections(10) if allowed(*refl)]
```

I use another package to calculate structure factors ([scikit-ued](LaurentRDC/scikit-ued)), so you may either re-use that or copy the code from there.

If you want to do this often, and you have some time on your hands, you may want to contribute such functionality in `crystals` :)

**Comment by LaurentRDC** [comment]
I just tried to implement it, and now I remember why it's not there: the calculation of structure factors (required to determine forbidden reflections) is dependent on the scattering method you use. Neutron, X-ray, and electron scattering factors are all different

**Comment by StarostinV** [comment]
Thank you for your answer and explanation! As far as I understand, the only difference is the calculation of atomic form factors. So it seems quite easy to extend the existing function in your package scikit-ued. So far I found a workaround with periodictable package which is more x-ray/neutrons related. I am not sure though whether you would agree to add that to your dependencies.

**Comment by LaurentRDC** [comment]
I don't want to add another dependency only for this feature, sorry. 

Feel free to re-open this issue if you find a solution that is not based on scattering technique, e.g. via spglib
