### ISSUE TITLE
Is Crystals correctly reading cif files?

### ISSUE THREAD

**Issue by errhernandez** [LaurentRDC/crystals#5]
Hello, 

I just downloaded Crystals, which looks very good and useful. However, playing around with it I found something that looks suspicious when reading a cif file. Specifically, the cif file is entry 1521011 from COD, which is the structure of a magnesium silicate of composition MgSiO3. Reading either the cif file directly, or else querying the COD database through Crystal.from_cod() command consistently gives the same result, but this result is wrong; the loaded structure has 21 atoms (4 Mg, 4 Si and 13 O) when the correct number should be 20 (only 12 O). I wonder if the problem is related to the fact that the cif file reports the structure in a non-standard setting? 

Incidentally, loading the cif file with ASE gives the correct structure with 20 atoms. 

Cheers, 

Eduardo

**Comment by LaurentRDC** [comment]
Hmm that is problematic. I will look into it.

**Comment by errhernandez** [comment]
Just in case it is useful, I installed through pip.

**Comment by LaurentRDC** [comment]
I have found the problem: When building the crystal for MgSiO3, the 21st Oxygen atom is almost identical to the 20th one, but a rounding error is preventing `crystals` from detecting it as a duplicate:

```
>>> from crystals import Crystal
>>> print(repr(Crystal.from_cod(1521011)))
< Crystal object with following unit cell:
    Atom Mg @ (0.02, 0.92, 0.75) | [1s²2s²2p⁶3s²]
    Atom Mg @ (0.98, 0.08, 0.25) | [1s²2s²2p⁶3s²]
    Atom Mg @ (0.48, 0.42, 0.75) | [1s²2s²2p⁶3s²]
    Atom Mg @ (0.52, 0.58, 0.25) | [1s²2s²2p⁶3s²]
    Atom O  @ (0.11, 0.48, 0.25) | [1s²2s²2p⁴]
    Atom O  @ (0.89, 0.52, 0.75) | [1s²2s²2p⁴]
    Atom O  @ (0.39, 0.98, 0.25) | [1s²2s²2p⁴]
    Atom O  @ (0.19, 0.19, 0.56) | [1s²2s²2p⁴]
    Atom O  @ (0.69, 0.31, 0.44) | [1s²2s²2p⁴]
    Atom O  @ (0.31, 0.69, 0.94) | [1s²2s²2p⁴]
    Atom O  @ (0.81, 0.81, 0.06) | [1s²2s²2p⁴]
    Atom O  @ (0.81, 0.81, 0.44) | [1s²2s²2p⁴]
    Atom O  @ (0.31, 0.69, 0.56) | [1s²2s²2p⁴]
    Atom O  @ (0.19, 0.19, 0.94) | [1s²2s²2p⁴]
    Atom O  @ (0.69, 0.31, 0.06) | [1s²2s²2p⁴]
    Atom O  @ (0.61, 0.02, 0.75) | [1s²2s²2p⁴]          <----
    Atom O  @ (0.61, 0.02, 0.75) | [1s²2s²2p⁴]          <----
    Atom Si @ (0.50, 0.00, 0.50) | [1s²2s²2p⁶3s²3p²]
    Atom Si @ (0.00, 0.50, 0.50) | [1s²2s²2p⁶3s²3p²]
    Atom Si @ (0.00, 0.50, 0.00) | [1s²2s²2p⁶3s²3p²]
    Atom Si @ (0.50, 0.00, 0.00) | [1s²2s²2p⁶3s²3p²]
Lattice parameters:
    a=4.445Å, b=4.665Å, c=6.454Å
    α=90.000°, β=90.000°, γ=90.000°
Chemical composition:
    O: 61.905%
    Mg: 19.048%
    Si: 19.048%
Source:
    C:\Users\Laurent\OneDrive\Bureau\1521011.cif >
```

I am working on a fix right now.

**Comment by LaurentRDC** [comment]
As of version 1.2.0, this issue should be resolved! The tests are currently passing, except for python 3.9 for a known and unrelated reason.

Don't hesitate to re-open this issue if it persists
