### ISSUE TITLE
Problem dealing with occupancies including error bar?

### ISSUE THREAD

**Issue by errhernandez** [LaurentRDC/crystals#7]
Dear Laurent, 

Thank you for this excellent facility. I have come across a little problem when reading certain .cif files that include errors in parenthesis in occupancies for atoms in the cell using Crystal.from_cif(). I attach one such example. The error I get is this:

crystal = Crystal.from_cif( filename.cif )   # filename.cif = file in the attachment 
[filename.cif.gz](https://github.com/LaurentRDC/crystals/files/6726851/filename.cif.gz)

~/opt/anaconda3/lib/python3.8/site-packages/crystals/crystal.py in from_cif(cls, path, **kwargs)
    126             return cls(
    127                 unitcell=symmetry_expansion(
--> 128                     parser.atoms(), parser.symmetry_operators()
    129                 ),
    130                 lattice_vectors=parser.lattice_vectors(),

~/opt/anaconda3/lib/python3.8/site-packages/crystals/parsers.py in atoms(self)
    702 
    703         atoms = list()
--> 704         for e, x, y, z, occ in zip(elements, xs, ys, zs, occupancies):
    705             coords = np.array(
    706                 [

ValueError: could not convert string to float: '0.707(2)'

I thought you might like to know about this and I think it should be easy to correct. 

Thank you!

Eduardo

**Comment by LaurentRDC** [comment]
Thank you for your report! I have fixed it and included your CIF file as a test case to ensure this never happens again.

Look out for version 1.3.2, which will include this bug-fix. It will be released today.

**Comment by errhernandez** [comment]
Thank you for your speedy response. I look forward to the release. Best wishes.

**Comment by LaurentRDC** [comment]
Release 1.3.2 is live. Please let me know if it works for you

**Comment by errhernandez** [comment]
I will first thing in the morning. Thank you.

Eduardo R. Hernandez
Instituto de Ciencia de Materiales de Madrid (ICMM)
Consejo Superior de Investigaciones Científicas (CSIC)
Campus de Cantoblanco
28049 Madrid

tel: +34 91 3348994
email: ***@***.***
http://www.icmm.csic.es/ehernandez

**Comment by LaurentRDC** [comment]
I'll close this for now but don't hesitate to reopen if the problem persists.
